version: '3.7'

services:
  mqtt2influxdb:
    image: tagelus/mqtt2influxdb:latest
    container_name: mqtt2influxdb
    restart: always
    environment:
      - LOG_LEVEL=DEBUG
      - MQTT_ADDRESS=192.168.2.61
      - MQTT_TOPIC=esp32/#
      - INFLUXDB_ADDRESS=192.168.2.61
      - INFLUXDB_PORT=8086
